import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {shuffledIndices,isCorrect,rateCard,queueCards,parseProgress,EMPTY} from '../lib/learning.ts';
test('all actual question types preserve their original answer keys after display shuffling',()=>{
 const index=JSON.parse(fs.readFileSync(new URL('../public/data/index.json',import.meta.url)));
 let count=0;
 for(const c of index.courses){const d=JSON.parse(fs.readFileSync(new URL('../public/data/'+c.id+'.json',import.meta.url)));for(const q of d.questions){const order=shuffledIndices(q.id,q.options.length);assert.equal(new Set(order).size,q.options.length);assert.deepEqual([...order].sort((a,b)=>a-b),q.options.map((_,i)=>i));assert.equal(isCorrect(q,q.correct),true,q.id);assert.equal(isCorrect(q,[]),false,q.id);if(q.type==='order')assert.equal(isCorrect(q,[...q.correct].reverse()),false,q.id);if(q.type==='multi')assert.equal(isCorrect(q,q.correct.slice(1)),false,q.id);count++}}
 assert.equal(count,8944);
});
test('fixed intervals and review counts are exact',()=>{const now=Date.parse('2026-09-20T12:00:00Z');const again=rateCard(undefined,'Again',now);assert.equal(again.due,'2026-09-20T12:10:00.000Z');assert.equal(again.count,1);const good=rateCard(again,'Good',now);assert.equal(good.due,'2026-09-23T12:00:00.000Z');assert.equal(good.count,2);assert.throws(()=>rateCard(undefined,'Unknown',now));});
test('recall queue puts due before new and excludes future cards',()=>{const now=Date.parse('2026-09-20T12:00:00Z');const cards=[{id:'new'},{id:'future'},{id:'recent'},{id:'old'}];const reviews={future:{due:'2026-09-21T00:00:00Z'},recent:{due:'2026-09-20T12:00:00Z'},old:{due:'2026-09-19T09:00:00-04:00'}};assert.deepEqual(queueCards(cards,reviews,now).map(c=>c.id),['old','recent','new']);});
test('backup round-trips quiz answers and recall dates without retaining unknown fields',()=>{const p={schema:1,completed:['DCCA-L04'],attempts:{'DCCA-Q001':{correct:true,answer:[2],at:'2026-09-20T12:00:00Z'}},reviews:{'DCCA-C001':rateCard(undefined,'Hard',0)}};assert.deepEqual(parseProgress(JSON.parse(JSON.stringify(p))),p);assert.deepEqual(parseProgress({...EMPTY,unexpected:'ignored'}),EMPTY);assert.throws(()=>parseProgress({...EMPTY,schema:9}));assert.throws(()=>parseProgress({...EMPTY,reviews:{card:{rating:'Good',due:'bad'}}}));});
test('all equipment routes point to existing chapters and all source learning IDs are unique',()=>{const index=JSON.parse(fs.readFileSync(new URL('../public/data/index.json',import.meta.url)));const systems=JSON.parse(fs.readFileSync(new URL('../public/data/systems.json',import.meta.url))).systems;const ids=new Set();for(const c of index.courses){const d=JSON.parse(fs.readFileSync(new URL('../public/data/'+c.id+'.json',import.meta.url)));for(const l of d.lessons){assert.ok(!ids.has(l.id));ids.add(l.id);for(const card of l.cards){assert.ok(!ids.has(card.id));ids.add(card.id)}}for(const q of d.questions){assert.ok(!ids.has(q.id));ids.add(q.id);for(const l of q.lesson_ids)assert.ok(d.lessons.some(x=>x.id===l),q.id)}}assert.equal(systems.length,6);for(const s of systems){assert.equal(s.components.length,4);for(const c of s.components){assert.equal(c.lessons.length,3);for(const l of c.lessons)assert.ok(index.courses.find(c=>c.id===l.courseId)?.lessons.some(x=>x.id===l.lessonId))}}});
test('concurrent tabs retain unrelated changes and preserve deliberate read/unread edits',async()=>{const {mergeProgress}=await import('../lib/learning.ts');const latest={...EMPTY,completed:['DCCA-L01'],attempts:{Q1:{correct:true,answer:[1],at:'2026-09-20T12:00:00Z'}}};const next={...EMPTY,completed:['DCCA-L02']};const merged=mergeProgress(EMPTY,next,latest);assert.deepEqual(merged.completed,['DCCA-L01','DCCA-L02']);assert.ok(merged.attempts.Q1);const unread=mergeProgress({...EMPTY,completed:['DCCA-L01']},EMPTY,merged);assert.deepEqual(unread.completed,['DCCA-L02']);});
