export type Review={rating:string;due:string;last_reviewed:string;count:number;interval_days:number};
export type Progress={schema:1;completed:string[];attempts:Record<string,{correct:boolean;answer:number[];at:string}>;reviews:Record<string,Review>};
export const EMPTY:Progress={schema:1,completed:[],attempts:{},reviews:{}};
export const STORAGE='inside-data-center-progress-v1';
export const INTERVALS:Record<string,number>={Again:10/1440,Hard:1,Good:3,Easy:7};
const cache=new Map<string,any>();
export async function loadCourse(id:string){if(!/^[A-Z0-9-]+$/.test(id))throw new Error('Invalid course');if(cache.has(id))return cache.get(id);const r=await fetch(`./data/${id}.json`);if(!r.ok)throw new Error('The course could not be loaded. Please try again.');const d=await r.json();cache.set(id,d);return d}
export function shuffledIndices(id:string,length:number){const a=Array.from({length},(_,i)=>i);let s=2166136261;for(const c of id)s=Math.imul(s^c.charCodeAt(0),16777619);for(let i=a.length-1;i>0;i--){s=(Math.imul(s,1664525)+1013904223)>>>0;const j=s%(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
export function isCorrect(q:any,answer:number[]){return q.type==='order'?JSON.stringify(answer)===JSON.stringify(q.correct):answer.length===q.correct.length&&q.correct.every((i:number)=>answer.includes(i))}
export function rateCard(previous:Review|undefined,rating:string,now=Date.now()):Review{if(!(rating in INTERVALS))throw new Error('Invalid rating');return {rating,last_reviewed:new Date(now).toISOString(),due:new Date(now+INTERVALS[rating]*86400000).toISOString(),interval_days:INTERVALS[rating],count:(previous?.count||0)+1}}
export function queueCards(cards:any[],reviews:Progress['reviews'],now=Date.now()){return cards.filter(c=>!reviews[c.id]||Date.parse(reviews[c.id].due)<=now).sort((a,b)=>{const ar=reviews[a.id],br=reviews[b.id];if(ar&&br)return Date.parse(ar.due)-Date.parse(br.due);return ar?-1:br?1:0})}
export function parseProgress(input:any):Progress{if(input?.schema!==1||!Array.isArray(input.completed)||!input.attempts||!input.reviews)throw new Error('This is not an Explorer progress backup.');const validId=(id:any)=>typeof id==='string'&&!['__proto__','constructor','prototype'].includes(id)&&/^[A-Za-z0-9_-]{1,100}$/.test(id);if(input.completed.length>2000||Object.keys(input.attempts).length>20000||Object.keys(input.reviews).length>10000)throw new Error('Backup exceeds the supported programme size.');const p:Progress={schema:1,completed:[...new Set<string>(input.completed.filter(validId))],attempts:{},reviews:{}};for(const [id,a] of Object.entries<any>(input.attempts)){if(!validId(id)||typeof a?.correct!=='boolean'||!Array.isArray(a.answer)||!a.answer.every((v:any)=>Number.isInteger(v)&&v>=0&&v<100)||!Number.isFinite(Date.parse(a.at)))throw new Error('Invalid quiz record.');p.attempts[id]={correct:a.correct,answer:a.answer,at:a.at}}for(const [id,r] of Object.entries<any>(input.reviews)){if(!validId(id)||!(r?.rating in INTERVALS)||!Number.isFinite(Date.parse(r.due))||!Number.isFinite(Date.parse(r.last_reviewed))||!Number.isInteger(r.count)||r.count<1||!Number.isFinite(r.interval_days)||r.interval_days<0)throw new Error('Invalid flashcard record.');p.reviews[id]={rating:r.rating,due:r.due,last_reviewed:r.last_reviewed,count:r.count,interval_days:r.interval_days}}return p}
// Apply only the current interaction's changes to the latest device record.
export function mergeProgress(base:Progress,next:Progress,latest:Progress):Progress{
 const added=next.completed.filter(id=>!base.completed.includes(id));const removed=new Set(base.completed.filter(id=>!next.completed.includes(id)));
 const merged:Progress={schema:1,completed:[...new Set([...latest.completed.filter(id=>!removed.has(id)),...added])],attempts:{...latest.attempts},reviews:{...latest.reviews}};
 for(const [id,a] of Object.entries(next.attempts)){if(JSON.stringify(a)!==JSON.stringify(base.attempts[id])&&(!merged.attempts[id]||Date.parse(a.at)>=Date.parse(merged.attempts[id].at)))merged.attempts[id]=a;}
 for(const [id,r] of Object.entries(next.reviews)){if(JSON.stringify(r)!==JSON.stringify(base.reviews[id])&&(!merged.reviews[id]||Date.parse(r.last_reviewed)>=Date.parse(merged.reviews[id].last_reviewed)))merged.reviews[id]={...r,count:Math.max(r.count,(merged.reviews[id]?.count||0)+1)};}
 return merged;
}
